POST http://localhost:8080/cats
Content-Type: application/json

{
  "name": "fishmaster",
  "type": "cat-fish"
}
###
POST http://localhost:8080/dogs
Content-Type: application/json

{
  "name": "doggymaster",
  "type": "dog-fish"
}
###
POST http://localhost:8080/hamsters
Content-Type: application/json

{
  "name": "da hamster",
  "type": "master"
}
###
GET http://localhost:8080/admin/main
Authorization: Basic jack:1234

###
GET http://localhost:8080/login
Authorization: Basic jack:1234

###
GET http://localhost:8080/login?username=jack&password=1234
Content-Type: application/json
